Mine auctions
UnitBanking/unit-smart-contracts pull request #10
Opened 2023-12-18 09:38 UTC by aristotleee

2023-12-19 06:56 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        bidToken.transferFrom(msg.sender, bondingCurve, amount);
We should also consider looking at safeTransferFrom and checking the return value: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/5bca2119ca634a0f7df4e2c3abf468e90c614119/contracts/token/ERC20/utils/SafeERC20.sol#L45C9-L45C28

2023-12-19 07:41 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        uint256 i = 0;
No need to initialize with 0

2023-12-19 07:41 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        for (; i < period; i++) {
Hmmm, maybe instead of loop this should be done with straight math 2**period?

2023-12-19 07:41 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        return (auctionableAmount * (currentAuctionId + 1)) / 1460;
What is 1460? Let's refactor into a constant

2023-12-19 07:41 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        return (auctionableAmount * (currentAuctionId + 1)) / 1460;
This looks a bit clumsy - lets save it as a local and then subtract 1 as needed but not sub and then add
uint256 currentAuctionId = nextAuctionId - 1;
currentAuctionId + 1

2023-12-19 07:41 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        return (auctionableAmount * (currentAuctionId + 1)) / 1460;
What's the purpose of multiply by * (currentAuctionId + 1)?

2023-12-19 08:05 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +                initializeAuction(auctionId);
💬 Discussion
This looks like an optimization to pack auctions, but I wonder if it's needed.

2023-12-19 08:43 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +                block.timestamp >= auctionStartTime
We can change the order of the checks to fail a bit quicker with less computation

  block.timestamp < auctionStartTime + auctionInterval - auctionSettleTime &&
                block.timestamp >= auctionStartTime

->

                block.timestamp >= auctionStartTime &&  block.timestamp < auctionStartTime + auctionInterval - auctionSettleTime

2023-12-19 08:43 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function revertIfNotInSettlement() internal view {
The function is called revertIfNotInSettlement but the error is AuctionBiddingInProgress - maybe we should sync the two?

function revertIfAuctionBiddingInProgress

2023-12-19 08:45 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +            return;
💬 Discussion
Not sure we should allow claiming zero

2023-12-19 08:45 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +            amount = claimable;
💬 Discussion
Not sure we should truncate claiming amount

2023-12-19 08:46 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        if (auctionElapsed < auctionDuration && auctions[auctionId].totalBidAmount == 0) {
I feel we should refactor this logic for more clarity and to also declutter the bid function.

2023-12-19 08:48 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        totalAuctionableAmount = (mine.MAX_SUPPLY() * 80) / 100;
I'm not sure there's much of a benefit of saving this variable?

2023-12-19 08:50 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    uint256 public override auctionSettleTime;
Let's at least group variables by global configuration versus auction instance variables and sort them hierarchically:

uint256 public totalAuctionableAmount;
uint256 public initialAuctionTime;
uint256 public override auctionInterval;
uint256 public override auctionSettleTime;

uint256 public override nextAuctionId;
uint256 public override auctionStartTime;

2023-12-19 10:27 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function bid(uint256 amount) external override {
I wonder if bid should also take an auction id, so that people don't accidentally submit a bid ten but have it mined for the wrong auction

2023-12-19 13:08 UTC, ivebeenherebefore commented
💬 Discussion
Right now, we try to lazy initialize auctions using the bid function. I wonder if we can write the SC so that the auctions are entirely automatic and don't require any lazy initialization. The idea would be to:

• set a start date (for the first auction), auction interval, auction settlement (although I'd like to redefine this parameter later)
• create functions that deterministically compute the auction reward, auction number (primary key), and auction timestamps without the need for ongoing initialization
• writing methods would be bid(auction id, uint256 amount) and claim(auction id, uint256 amount)
• reading methods would be auctionId(uint256 timestamp), auctionReward(uint256 auctionId), auctionTimestamps(uint256 auctionId)

2023-12-21 00:22 UTC, franklynot commented on contracts/MineAuction.sol
> +        bidToken.transferFrom(msg.sender, bondingCurve, amount);
+1 on both points.
Regarding handling of any external tokens, like the `bidToken`, let's use OZ's SafeERC20:
```
using SafeERC20 for IERC20
```

2023-12-21 00:31 UTC, franklynot commented on contracts/MineAuction.sol
> +    function setBondingCurve(address _bondingCurve) external onlyOwner {
How often do we expect this to change? If very rarely, then it can be updated via a SC upgrade.

2023-12-21 00:31 UTC, franklynot commented on contracts/MineAuction.sol
> +    function setBidToken(address _bidToken) external onlyOwner {
How often do we expect this to change? If very rarely, then can be updated via a SC upgrade.

2023-12-21 00:33 UTC, franklynot commented on contracts/MineAuction.sol
> +    function setMine(address _mine) external onlyOwner {
MINE is behind a proxy, so no changes are expected.

2023-12-21 00:40 UTC, franklynot commented on contracts/MineAuction.sol
> +            return;
I think we should. The function can be called with zero amount due to rounding on the caller side or other reasons where the amount happens to be a result of an expression. I don't think we should revert just because it  works out to zero.
Furthermore, we should probably follow the ERC20 convention and execute the full flow (including minting and emitting all the events with zero amount). We're doing it in the `BondingCurve`.

2023-12-21 00:44 UTC, franklynot commented on contracts/MineAuction.sol
> +import './interfaces/IAuction.sol';
I think it's fine. It's a generic auction interface (no function mentions MINE).

2023-12-21 08:52 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        bidToken.transferFrom(msg.sender, bondingCurve, amount);
Let's refactor this transfer (and others) into a library, where we are doing safeTransferFrom and there's a comment for why we skipped the balance checks. That way if we need to add balance checks later, we can just do it in the library instead of updating the contract everywhere.

2023-12-27 15:20 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function revertIfNotInSettlement() internal view {
Fixed

2023-12-27 15:20 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function _claim(address bidder, address to, uint256 auctionId, uint256 amount) internal {
Fixed

2023-12-27 15:21 UTC, aristotleee commented on contracts/MineAuction.sol
> +        auctions[auctionId].bid[msg.sender] = amount;
Fixed

2023-12-27 15:25 UTC, aristotleee commented on contracts/MineAuction.sol
> +        totalBidAmount = auctions[auctionId].totalBidAmount;
`Auction memory auction = auctions[auctionGroupId][auctionId];`

will trigger an compiler error
> Type struct IMineAuction.Auction memory is only valid in storage because it contains a (nested) mapping.

2023-12-27 15:28 UTC, aristotleee commented on contracts/MineAuction.sol
> +import './interfaces/IAuction.sol';
@franklynot Our original idea is use this interface for both MineAuction and UnitAuction. I think that's not gonna happen now since the underneath mechanisms are not the same

Changed the name to IMineAuction

2023-12-27 15:29 UTC, aristotleee commented on contracts/MineAuction.sol
> +    uint256 public override auctionSettleTime;
Refactored

2023-12-27 15:29 UTC, aristotleee commented on contracts/MineAuction.sol
> +                block.timestamp >= auctionStartTime
Refactored

2023-12-27 15:30 UTC, aristotleee commented on contracts/MineAuction.sol
> +        if (auctionElapsed < auctionDuration && auctions[auctionId].totalBidAmount == 0) {
Refactored

2023-12-27 15:30 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function bid(uint256 amount) external override {
Refactored

2023-12-27 15:30 UTC, aristotleee commented on contracts/MineAuction.sol
> +            initialAuctionTime = block.timestamp;
Refactored

2024-01-02 06:13 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +import './interfaces/IAuction.sol';
I don't see the change committed yet

2024-01-02 06:14 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function setMine(address _mine) external onlyOwner {
Agreed, let's not make it mutable.

2024-01-08 04:56 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +import './interfaces/IAuction.sol';
The import needs to be fixed right, it should say IMineAuction.sol?

2024-01-08 05:00 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function setBidToken(address _bidToken) external onlyOwner {
Let's remove this for now. There would be issues with setting this out of sync with the state of the internal contract. It'll be easier to just remove this rather than deal with all the corner cases.

2024-01-08 05:29 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +            if (interval - settleTime <= MINIMUM_AUCTION_INTERVAL) {
This is slightly confusing. We need to make sure we're communicating that the MINIMUM_AUCTION_INTERVAL is interval - settle time.

2024-01-08 05:29 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        totalBidAmount = auctions[auctionGroupId][auctionId].totalBidAmount;
Should we revert if auctionGroupId or auctionId doesn't exist yet?

2024-01-08 05:29 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        bidAmount = auctions[auctionGroupId][auctionId].bid[bidder];
Should we revert if auctionGroupId or auctionId doesn't exist yet?

2024-01-08 05:29 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        claimedAmount = auctions[auctionGroupId][auctionId].claimed[bidder];
Should we revert if auctionGroupId or auctionId doesn't exist yet?

2024-01-08 05:29 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        auctions[currentAuctionGroupId()][auctionId].totalBidAmount += amount;
Should we cache currentAuctionGroupId() into local variable?

2024-01-08 05:29 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        totalBidAmount = auctions[auctionGroupId][auctionId].totalBidAmount;
It seems we're missing a lazy initialiation here?

        if (auctions[currentAuctionGroupId()][auctionId].rewardAmount == 0) {
            auctions[currentAuctionGroupId()][auctionId].rewardAmount = getRewardAmount();
        }

2024-01-08 07:19 UTC, stardustPandora commented on contracts/MineAuction.sol
> +import './interfaces/IAuction.sol';
fixed

2024-01-08 07:20 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function setMine(address _mine) external onlyOwner {
left as this deliberately to write test cases, before precompile added

2024-01-08 07:20 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function setBidToken(address _bidToken) external onlyOwner {
left as this deliberately to write test cases, before precompile added

2024-01-08 07:20 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function setBondingCurve(address _bondingCurve) external onlyOwner {
left as this deliberately to write test cases, before precompile added

2024-01-08 07:20 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        totalBidAmount = auctions[auctionId].totalBidAmount;
Fixed

2024-01-08 07:20 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        bidToken.transferFrom(msg.sender, bondingCurve, amount);
Fixed

2024-01-08 07:20 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        uint256 i = 0;
Fixed

2024-01-08 07:20 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        for (; i < period; i++) {
Fixed

2024-01-08 07:21 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        totalAuctionableAmount = (mine.MAX_SUPPLY() * 80) / 100;
Fixed

2024-01-08 07:21 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        totalBidAmount = auctions[auctionGroupId][auctionId].totalBidAmount;
if there is bid for that auction, then it will be initialized, other wise it is left lazy empty

2024-01-08 07:22 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        bidAmount = auctions[auctionGroupId][auctionId].bid[bidder];
for normal user case( read from frontend), it will give the right amount, for other cases, like read not existed auction, just return zero should be fine

2024-01-08 07:22 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        auctions[currentAuctionGroupId()][auctionId].totalBidAmount += amount;
fixed

2024-01-10 04:06 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function setMine(address _mine) external onlyOwner {
fixed

2024-01-10 04:06 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function setBidToken(address _bidToken) external onlyOwner {
fixed

2024-01-10 04:06 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function setBondingCurve(address _bondingCurve) external onlyOwner {
fixed

2024-01-10 04:07 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        return (auctionableAmount * (currentAuctionId + 1)) / 1460;
fixed

2024-01-10 04:08 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        return (auctionableAmount * (currentAuctionId + 1)) / 1460;
fixed

2024-01-10 04:09 UTC, stardustPandora commented on contracts/MineAuction.sol
> +            amount = claimable;
should revert with invalid claim amount 

fixed

2024-01-10 05:58 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        bidAmount = auctions[auctionGroupId][auctionId].bid[bidder];
fixed

2024-01-10 06:00 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        claimedAmount = auctions[auctionGroupId][auctionId].claimed[bidder];
fixed

2024-01-10 06:49 UTC, aristotleee commented on contracts/MineAuction.sol
> +        return (auctionableAmount * (currentAuctionId + 1)) / 1460;
Refactored by @stardustPandora

2024-01-10 06:54 UTC, aristotleee commented on contracts/MineAuction.sol
> +            return;
Fixed to execute whole flow

2024-01-10 07:05 UTC, aristotleee commented on contracts/MineAuction.sol
> +            if (interval - settleTime <= MINIMUM_AUCTION_INTERVAL) {
interval - settleTime is the bid duration time, we are trying to make sure it's not too small

2024-01-10 07:12 UTC, aristotleee commented on contracts/MineAuction.sol
> +        totalBidAmount = auctions[auctionGroupId][auctionId].totalBidAmount;
The current fix can only revert when the Id is larger than current possible. If a certain auction is skipped, `getAuction` will still return with 0

2024-01-10 07:14 UTC, aristotleee commented on contracts/MineAuction.sol
> +        bidAmount = auctions[auctionGroupId][auctionId].bid[bidder];
_Same as previous_

The current fix can only revert when the auctionId is larger than current possible. If a certain auction is skipped, getAuction will still return with 0

Group will be continuous, there won't be any skipped ones

2024-01-10 07:14 UTC, aristotleee commented on contracts/MineAuction.sol
> +        claimedAmount = auctions[auctionGroupId][auctionId].claimed[bidder];
_Same as previous_

The current fix can only revert when the auctionId is larger than current possible. If a certain auction is skipped, getAuction will still return with 0

Group will be continuous, there won't be any skipped ones

2024-01-11 07:54 UTC, ivebeenherebefore requested changes

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        initialAuctionTime = block.timestamp;
Probably we just want to pass this in as a parameter to the initializer.

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        initialAuctionTime = _initialAuctionTime;
This is unsafe to change this right? We shouldn't make it mutable.

If we define any kind of setter, we need to guarantee it cannot be set out of phase with reverts or checks of some kind.

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    uint256 public initialAuctionTime;
We can't make these immutable since they need to be set via the initialize function, huh?

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +            if (interval - settleTime <= MINIMUM_AUCTION_INTERVAL) {
This is still confusing. Either MINIMUM_AUCTION_INTERVAL should be renamed as MINIMUM_AUCTION_DURATION or the math is still not intuitive. The revert is even more confusing, its saying the settle time is invalid: AuctionInvalidSettleTime.

💬
Let's discuss this. I'm thinking we should replace interval + settleTime and use interval + duration or duration + settleTime.

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function getAuctionGroup(
If I'm not mistaken, we could just make the mapping public.

💬 Discussion: when to define getters versus making storage public?

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/interfaces/IMineAuction.sol
> +        mapping(address bidder => uint256 claimedAmount) claimed;
I wonder if we should b using one mapping to a nested struct vs multiple mappings? Is there a storage or gas benefit? Can bid and claimed be packed?

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function getClaimed(
💬 Discussion
Also not sure if we should combine getBid, getClaimed, getClaimable.

Might make sense to create the following to make getting all data easier:
function getAuction(uint256 auctionGroupId, uint256 auctionId, address bidder) returns (uint256 totalBidAmount, uint256 rewardAmount, uint256 bidAmount, uint256 claimedAmount, uint256 claimableAmount) {
}

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    ) external view override returns (uint256 totalBidAmount, uint256 rewardAmount) {
💬 Discussion

This is a bit strange that rewardAmount isn't returned. It seems there are two use cases:

1. During or before the auction, on the frontend we need to display how much is being auctioned off. In this case, rewardAmount cannot be 0.

2. After the auction, the frontend will look at past auctions and list how many tokens were auctioned off. If there were no bidders, then rewardAmount should be 0.

We need a way to support both cases. Either this function become polymorphic or we provide two separate view functions.

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    ) external view override returns (uint256 totalBidAmount, uint256 rewardAmount) {
We may also need additional stats like when an auction starts and how long it will last for.

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        TransferHelper.safeTransferFrom(bidToken, msg.sender, address(bondingCurve), amount);
💬 Discussion
This is still not using balance checkpointing to determine amount.

Maybe we should rewrite TransferHelper.safeTransferFrom to return the transferred amount. It will either do checkpointing under the hood or just return the input amount.

Right now if we decide we need to use checkpointing, we need to actually rewrite this function logic.

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        unchecked {
This needs a comment that states when this will overflow. Eventually it will overflow.

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +            uint256 previousAuctionDuration = auctionId * auctionGroup.interval;
previousAuctionDuration  -> previousAuctionDurations

Again, "durations" here is misused. This is really totalAuctionIntervals not SUM(intervals - settleTime)

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        uint256 previousAuctionDuration = auctionId * auctionGroup.interval;
💬 Discussion
How do we know if an auction id is part of a particular auctionGroup or if it's part of a latter auctionGroup.

It seems we need to check auctionGroup id + 1.startTime

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        uint256 period = ((block.timestamp - initialAuctionTime) / SECONDS_IN_FOUR_YEARS) + 1;
Store block.timestamp - initialAuctionTime in local var?

2024-01-11 07:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function getClaimableAmount(
Note about combining into getters above

2024-01-11 08:03 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        auctionGroup.startTime = startTime;
Don't we need to ensure the startTime is > current block time?

2024-01-11 08:10 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +contract MineAuction is Ownable, IMineAuction, Proxiable {
💬 Discussion add re-entrancy guards

2024-01-11 08:34 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +            if (interval - settleTime <= MINIMUM_AUCTION_INTERVAL) {
totalDuration = bidDuration + settleDuration

2024-01-11 08:37 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +            if (interval - settleTime <= MINIMUM_AUCTION_INTERVAL) {
Let's remove MINIMUM_AUCTION_INTERVAL since it's not needed

2024-01-11 08:40 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function currentAuctionGroupId() public view override returns (uint256) {
We assume current auction group is always active, but in actuality we may create an auction group in the future, in which case the startTime may not have been triggered yet.

2024-01-11 08:41 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        validateAuctionGroupId(auctionGroupId);
This shouldn't be validated, since we may want to fetch future auction groups.

2024-01-11 08:42 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function getAuctionGroup(
Up to us if we want to make this a public array versus adding a getter here.

2024-01-11 08:46 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +contract MineAuction is Ownable, IMineAuction, Proxiable {
We need to make bidding pausable.

2024-01-11 08:50 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +            if (interval - settleTime <= MINIMUM_AUCTION_INTERVAL) {
We need to add the following checks to enforce always ascending startTimes on groups:

• when w new group is added, we need to check the group before it and ensure the ordering of start times:
prev.startTime < new.startTime

2024-01-11 08:54 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function setAuctionGroup(uint256 startTime, uint256 settleTime, uint256 interval) external override onlyOwner {
setAuctionGroup needs to be callable out of phase. So the only real constraint is that the start time needs to be in the future and during a settleTime (in the future) so that it ideally doesn't cut short any auctions.

2024-01-11 09:05 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        TransferHelper.safeTransferFrom(bidToken, msg.sender, address(bondingCurve), amount);
function TransferHelper.safeTransferFrom(bidToken, msg.sender, address(bondingCurve), amount) return (amountTransferred) {
  balanceBefore=
  do transfer
  balanceAfter=
return balanceAfter - balanceBefore
}

2024-01-11 10:40 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    ) external view override returns (uint256 totalBidAmount, uint256 rewardAmount) {
Also not sure if we should combine getBid, getClaimed, getClaimable.

Might make sense to create the following to make getting all data easier:
function getAuction(uint256 auctionGroupId, uint256 auctionId, address bidder) returns (uint256 totalBidAmount, uint256 rewardAmount, uint256 bidAmount, uint256 claimedAmount, uint256 claimableAmount) {
}

2024-01-11 10:41 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    ) external view override returns (uint256 totalBidAmount, uint256 rewardAmount) {
In conclusion, we decided to keep the individual functions but also add a combined function that can call these sub functions to return a "batched" fetch for the frontend. We may need to add additional fields like when the auction will start and when it will end and be claimable, etc. Please think through the data we'll need from view functions.

2024-01-17 08:45 UTC, aristotleee commented on contracts/MineAuction.sol
> +        initialAuctionTime = block.timestamp;
Fixed, use constructor parameter

2024-01-17 08:45 UTC, aristotleee commented on contracts/MineAuction.sol
> +        initialAuctionTime = _initialAuctionTime;
Removed `setIntialAuctionTime`

2024-01-17 08:56 UTC, aristotleee commented on contracts/MineAuction.sol
> +    ) external view override returns (uint256 totalBidAmount, uint256 rewardAmount) {
`getAuctionInfo` added

2024-01-17 08:58 UTC, aristotleee commented on contracts/MineAuction.sol
> +        TransferHelper.safeTransferFrom(bidToken, msg.sender, address(bondingCurve), amount);
Fixed, using return value of `safeTransferFrom` as bid amount

2024-01-17 09:02 UTC, aristotleee commented on contracts/MineAuction.sol
> +        unchecked {
Fixed to remove unchecked since the parameter `auctionId` will cause overflow

2024-01-17 09:06 UTC, aristotleee commented on contracts/MineAuction.sol
> +            uint256 previousAuctionDuration = auctionId * auctionGroup.interval;
Fixed, use `settleTime`, `bidTime` in auctionGroup. which entire auctionDuration = settleTime + bidTime

2024-01-17 09:16 UTC, aristotleee commented on contracts/MineAuction.sol
> +        uint256 period = ((block.timestamp - initialAuctionTime) / SECONDS_IN_FOUR_YEARS) + 1;
Fixed

2024-01-17 09:16 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function getClaimableAmount(
Fixed

2024-01-17 09:34 UTC, aristotleee commented on contracts/MineAuction.sol
> +        uint256 previousAuctionDuration = auctionId * auctionGroup.interval;
Fixed

2024-01-17 09:35 UTC, aristotleee commented on contracts/MineAuction.sol
> +        auctionGroup.startTime = startTime;
it's checked in external function

2024-01-17 09:41 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function currentAuctionGroupId() public view override returns (uint256) {
how many future auction group is allowed?

2024-01-17 09:44 UTC, aristotleee commented on contracts/MineAuction.sol
> +        validateAuctionGroupId(auctionGroupId);
Fixed

2024-01-17 09:59 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function setAuctionGroup(uint256 startTime, uint256 settleTime, uint256 interval) external override onlyOwner {
|-----|-*-?-|

The current setAuctionGroup only callable during settleTime, can set startTime to any time that is larger than current time, include the time inside settleTime

2024-01-18 08:23 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function currentAuctionGroupId() public view override returns (uint256) {
conclusion: make currentAuctionGroupId external, and add groupId param to bid

2024-01-22 05:59 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function setAuctionGroup(uint256 startTime, uint256 settleTime, uint256 interval) external override onlyOwner {
only allow startTime to be  in settlement of  previous auction

2024-01-22 05:59 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function currentAuctionGroupId() public view override returns (uint256) {
Fixed

2024-01-24 09:10 UTC, aristotleee commented on contracts/interfaces/IMineAuction.sol
> +    error AuctionAuctionIdTooLarge(uint256 auctionId);
Same here
Two conditions are
- auctionId is greater than current auctionId, valid when auctionId is history + current
    - `getAuction`, `getBid`, `getClaimed`, `getAuctionInfo`
- auctionId is greater and equal to current auctionId, valid when auctionId is in history
    - `claim`, `claimTo`

2024-01-24 09:10 UTC, aristotleee commented on contracts/MineAuction.sol
> +            revert AuctionInvalidClaimAmount(amount);
```suggestion
            revert AuctionInsufficientClaimAmount(amount);
```

insufficient is more accurate

2024-01-24 09:10 UTC, aristotleee commented on contracts/MineAuction.sol
> +import 'hardhat/console.sol';
oops

2024-01-25 07:18 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    // should be be able to fetch future auction
fixed

2024-01-25 07:18 UTC, stardustPandora commented on contracts/interfaces/IMineAuction.sol
> +    error AuctionAuctionGroupIdTooLarge(uint256 auctionGroupId);
fixed

2024-01-25 07:18 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        if (auctionGroupId > auctionGroups.length - 1) {
fixed

2024-01-25 07:18 UTC, stardustPandora commented on contracts/MineAuction.sol
> +            if (offset < auctionGroup.bidTime || startTime > block.timestamp - elapsed + auctionDuration) {
fixed

2024-01-25 07:18 UTC, stardustPandora commented on contracts/MineAuction.sol
> +            // Overflow not possible: auctionInterval > auctionSettleTime
fixed

2024-01-25 07:18 UTC, stardustPandora commented on contracts/MineAuction.sol
> +            uint256 offset = (startTime - auctionGroup.startTime) % auctionDuration;
fixed

2024-01-25 07:53 UTC, stardustPandora commented on contracts/MineAuction.sol
> +import 'hardhat/console.sol';
fixed

2024-01-25 07:53 UTC, stardustPandora commented on contracts/MineAuction.sol
> +            revert AuctionInvalidClaimAmount(amount);
fixed

2024-01-25 07:53 UTC, stardustPandora commented on contracts/interfaces/IMineAuction.sol
> +    error AuctionAuctionIdTooLarge(uint256 auctionId);
fixed

2024-01-25 07:55 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        if (!isCurrentAuctionId(auctionId)) {
fixed

2024-01-25 07:57 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        claimableAmount = getClaimableAmount(auctionGroupId, auctionId, bidder);
that would be ok, since from frontend they can see the bid is in progress, so while the bid progressing,  the claimable amount should change

2024-01-25 07:59 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        claimedAmount = auctions[auctionGroupId][auctionId].claimed[bidder];
this is normal, since u can not claim while a bidding is in progress, we can control the display in frontend

2024-01-25 08:18 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function revertIfAuctionIdInFuture(uint256 auctionGroupId, uint256 auctionId) internal view {
I don't think this is needed since this is a view function and these values are essentially auto increment

2024-01-25 08:19 UTC, stardustPandora commented on hardhat/test/auctions/auctionOperations.ts
> +  await ethers.provider.send('evm_mine')
if we do not  mine, this setNextBlockTimeStamp woud not take effect

2024-01-25 08:20 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function revertIfAuctionIdInFuture(uint256 auctionGroupId, uint256 auctionId) internal view {
then it will revert since overflow

2024-01-25 08:26 UTC, stardustPandora commented on contracts/interfaces/IMineAuction.sol
> +    }
fixed

2024-01-26 09:32 UTC, ivebeenherebefore requested changes

2024-01-26 09:32 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        AuctionGroup memory auctionGroup = auctionGroups[_currentAuctionGroupId()];
Line 145 uses a local var, why do we call it again?

2024-01-26 09:32 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        for (; auctionGroupId >= 0; auctionGroupId--) {
Although unlikely, this is a little bit of bad form to iterate over anything with an infinite length. We should look at a way to replace the need to do this.

2024-01-26 09:32 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function bid(uint256 auctionId, uint256 amount) external override onlyNotPaused {
We should pass auction group id, so that we do not need to call _currentAuctionGroupId

2024-01-26 09:32 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        uint currentGroupId = _currentAuctionGroupId();
Remove call to _currentAuctionGroupId

2024-01-26 12:36 UTC, StarDumpling commented on contracts/interfaces/IMineAuction.sol
> +    error AuctionNoDirectTransfer();
Since we have more that one auction in the protocol, we should add a prefix to errors thrown in this contract.
```suggestion
    error MineAuctionNoDirectTransfer();
```

2024-01-26 12:57 UTC, StarDumpling commented on contracts/MineAuction.sol
> +    IERC20 public bidToken;
It's unlikely those addresses will change so we could make them constant (immutable) and initialize in constructor.
This will save us some gas.

2024-01-26 15:17 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function revertIfAuctionIdInFuture(uint256 auctionGroupId, uint256 auctionId) internal view {
I think when the numbers get too big, it's okay to overflow. The key is to determine if this would really overflow in any meaningful amount of time.

2024-01-26 15:18 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        uint256 auctionGroupId = _currentAuctionGroupId();
Remove calls to currentAuctionGroupId

2024-01-26 16:00 UTC, StarDumpling commented on contracts/MineAuction.sol
> +contract MineAuction is Ownable, IMineAuction, Proxiable, Pausable {
I believe we should implement constructor that calls `Proxiable.initialize()` to prevent from initializing the implementation contract.

2024-01-28 08:03 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    IERC20 public bidToken;
Agreed

2024-01-28 19:04 UTC, aristotleee commented on contracts/MineAuction.sol
> +        AuctionGroup memory auctionGroup = auctionGroups[_currentAuctionGroupId()];
No longer applicable, refactored

2024-01-28 19:06 UTC, aristotleee commented on contracts/MineAuction.sol
> +        for (; auctionGroupId >= 0; auctionGroupId--) {
One possible solution is only allow one future auctionGroup, so the currentAuctionGroupId is either at auctionGroups.length - 1 or length - 2

2024-01-28 19:28 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function setAuctionGroup(uint256 startTime, uint256 settleTime, uint256 interval) external override onlyOwner {
@ivebeenherebefore @stardustPandora 
The current design only allows new startTime to be set within settleTime i.e.
OLD config: 00:00, 1 hour, 23 hours
ONLY possible new startTime: 23:00 - 23:59
one reasonable scenario 'let's do 5 minutes later than current auction', will not be available

I think we can just allow set new startTime at any time in the future, and disable bidding if current auction bidding phase is less than current group `bidTime`, the disable period will only last less than one `bidTime`

2024-01-29 07:34 UTC, stardustPandora commented on contracts/MineAuction.sol
> +contract MineAuction is Ownable, IMineAuction, Proxiable, Pausable {
fixed

2024-01-29 07:50 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    IERC20 public bidToken;
fixed

2024-01-29 07:52 UTC, stardustPandora commented on contracts/interfaces/IMineAuction.sol
> +    error AuctionNoDirectTransfer();
fixed

2024-02-02 06:18 UTC, timesaved12345 commented on contracts/MineAuction.sol
> +    uint256 constant SECONDS_IN_FOUR_YEARS = 4 * SECONDS_IN_YEAR;
1 year is 365 days, but 4 years is (4 * 365) + 1 days.

2024-02-02 06:25 UTC, timesaved12345 commented on contracts/MineAuction.sol
> +    uint256 public initialAuctionTime;
I think we can. As they won't be changed once set. And they can be set in constructor.

2024-02-02 07:19 UTC, timesaved12345 commented on contracts/MineAuction.sol
> +    function initialize(uint256 _initialAuctionTime) external {
Function `initialize(uint256 _initialAuctionTime)` is implementing the declaration in interface `IMineAuction`. The `override` keyword is not necessary since `Solidity 0.8.8`, but to be consistent, consider adding it back here.

2024-02-05 03:27 UTC, timesaved12345 commented on contracts/MineAuction.sol
> +                    (lastAuctionGroup.bidTime + lastAuctionGroup.settleTime);
Local variable `auctionStartTime` can be used instead of `lastAuctionGroup.startTime` in these few lines to save gas.

2024-02-05 07:45 UTC, timesaved12345 commented on contracts/MineAuction.sol
> +        Auction storage auction = auctions[auctionGroupId][auctionId];
Move this line to the beginning can save gas. Like this:

```
        Auction storage auction = auctions[auctionGroupId][auctionId];
        if (auction.totalBidAmount == 0) {
            return 0;
        }

```

2024-02-06 10:34 UTC, timesaved12345 commented on contracts/MineAuction.sol
> +        auctions[auctionGroupId][auctionId].bid[msg.sender] += transferAmount;
These few lines access the mapping multiple times. To save gas, we can use a storage local variable:
```
        Auction storage auction = auctions[auctionGroupId][auctionId]; // this is pointing to the storage, so you can directly read/write storage from here
        if (auction.rewardAmount == 0) {
            auction.rewardAmount = getRewardAmount(auctionGroupId);
        }
        ...
        auction.totalBidAmount += transferAmount;
        auction.bid[msg.sender] += transferAmount;
        
```

Sample code for using storage local variable, you can try it on remix:
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity ^0.8.0;

//24722
// contract Test {
//     mapping(uint => mapping(uint => string)) testMap;

//     function test() external {
//         mapping(uint => string) storage tempMap = testMap[1];
//         testMap[1][1] = "Hello";
//         tempMap[1] = "World";
//         require(false, tempMap[1]);
//     }
// }

//24788
contract Test {
    mapping(uint => mapping(uint => string)) testMap;

    function test() external {
        testMap[1][1] = "Hello";
        testMap[1][1] = "World";
        require(false, testMap[1][1]);
    }
}
```

2024-02-06 12:24 UTC, StarDumpling commented on contracts/MineAuction.sol
> +        initialized = true;
We have `initialize()` function in `Proxiable` contract, let's use it. 
```suggestion
        super.initialize();
```

2024-02-06 12:30 UTC, StarDumpling commented on contracts/MineAuction.sol
> +    uint256 public initialAuctionTime;
Right, we can save gas by making those immutable as we did with `bondingCurve`, `mine` and `bidToken`.

2024-02-06 12:30 UTC, StarDumpling commented on contracts/MineAuction.sol
> +    MineToken public immutable mine;
```suggestion
    MineToken public immutable mineToken;
```

2024-02-06 12:41 UTC, StarDumpling commented on contracts/MineAuction.sol
> +    receive() external payable {
Do we need this `receive()` function. If we remove it, direct eth transfer won't be possible either way.

2024-02-06 18:12 UTC, StarDumpling commented on contracts/MineAuction.sol
> +/// @dev The contract is proxiable and pauseable
[minor] I know that NatSpec format allows `///` for multi-line comments but could we change is to `/** */` to keep it consistent across the repo?
```suggestion
/**
 * @title MineAuction contract for auctioning MINE tokens
 * @notice You can use this contract to auction MINE tokens
 * @dev The contract is proxiable and pauseable
 */
```

2024-02-06 18:18 UTC, StarDumpling commented on contracts/MineAuction.sol
> +    /// @dev claim is only enabled for past auction, exclude current auction
This comment actually concerns `claim()` function.

2024-02-07 08:44 UTC, aristotleee commented on contracts/MineAuction.sol
> +    uint256 public initialAuctionTime;
Fixed

2024-02-07 08:45 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function getAuctionGroup(
made it external

2024-02-07 08:46 UTC, aristotleee commented on contracts/interfaces/IMineAuction.sol
> +        mapping(address bidder => uint256 claimedAmount) claimed;
No significant benefit to make it multiple mappings

2024-02-07 08:51 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function bid(uint256 auctionId, uint256 amount) external override onlyNotPaused {
Fixed

2024-02-07 08:51 UTC, aristotleee commented on contracts/MineAuction.sol
> +        uint currentGroupId = _currentAuctionGroupId();
Fixed

2024-02-07 08:52 UTC, aristotleee commented on contracts/MineAuction.sol
> +        uint256 auctionGroupId = _currentAuctionGroupId();
Fixed

2024-02-07 08:52 UTC, aristotleee commented on contracts/MineAuction.sol
> +    uint256 constant SECONDS_IN_FOUR_YEARS = 4 * SECONDS_IN_YEAR;
Fixed

2024-02-07 08:52 UTC, aristotleee commented on contracts/MineAuction.sol
> +    function initialize(uint256 _initialAuctionTime) external {
Now overriding Proxiable's `initialize()`

2024-02-07 08:52 UTC, aristotleee commented on contracts/MineAuction.sol
> +                    (lastAuctionGroup.bidTime + lastAuctionGroup.settleTime);
Fixed

2024-02-07 09:03 UTC, aristotleee commented on contracts/MineAuction.sol
> +        Auction storage auction = auctions[auctionGroupId][auctionId];
Fixed

2024-02-07 09:06 UTC, aristotleee commented on contracts/MineAuction.sol
> +        auctions[auctionGroupId][auctionId].bid[msg.sender] += transferAmount;
Fixed

2024-02-07 09:06 UTC, aristotleee commented on contracts/MineAuction.sol
> +    MineToken public immutable mine;
Fixed

2024-02-07 09:06 UTC, aristotleee commented on contracts/MineAuction.sol
> +/// @dev The contract is proxiable and pauseable
Fixed

2024-02-07 09:09 UTC, aristotleee commented on contracts/MineAuction.sol
> +    /// @dev claim is only enabled for past auction, exclude current auction
Fixed comments

2024-02-07 09:47 UTC, StarDumpling commented on contracts/MineAuction.sol
> +        Auction storage auction = auctions[auctionGroupId][auctionId];
Does it have to be `storage`? I guess we can change it to `memory`.
```suggestion
        Auction memory auction = auctions[auctionGroupId][auctionId];
```

2024-02-07 10:12 UTC, StarDumpling commented on contracts/MineAuction.sol
> +        claimableAmount = getClaimableAmount(auctionGroupId, auctionId, bidder);
We're reading auction from storage here in line 213 and we do the same in `getClaimableAmount()`.  Passing `auction` here could save some gas. We're also using this function in `_claim()`. We can also create a storage auction variable there and pass it. In case of a claim, it saves ~230 gas.
```suggestion
        claimableAmount = getClaimableAmount(auction, bidder);
```

2024-02-07 12:29 UTC, StarDumpling commented on contracts/interfaces/IMineAuction.sol
> +interface IMineAuction {
There's no tests that verifies:
`error MineAuctionCurrentAuctionDisabled`
`error MineAuctionInvalidBidAmount`
`error MineAuctionNotCurrentAuctionGroupId`
`error MineAuctionNoDirectTransfer`

2024-02-07 12:32 UTC, StarDumpling commented on hardhat/test/auctions/mine.test.ts
> +    it('allows to partial claim', async () => {})
Missing implementation.

2024-02-07 12:32 UTC, StarDumpling commented on hardhat/test/auctions/mine.test.ts
> +  it('can bid when auction is skipped', async () => {})
Missing implementation.

2024-02-07 12:35 UTC, StarDumpling commented on contracts/MineAuction.sol
> +    uint256 public totalAuctionableAmount;
I think this also can be immutable.
```suggestion
    uint256 public immutable totalAuctionableAmount;
```

2024-02-07 12:43 UTC, StarDumpling commented on contracts/MineAuction.sol
> +    uint256 constant SECONDS_IN_FOUR_YEARS = 4 * SECONDS_IN_YEAR + 1;
As @timesaved12345 mentioned, we need to add 1 day since every 4 years there is a leap year. 
```suggestion
    uint256 constant SECONDS_IN_FOUR_YEARS = 4 * SECONDS_IN_YEAR + 1 days;
```

2024-02-08 03:37 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    uint256 public totalAuctionableAmount;
It's set via initialize, so I don't think it can be immutable. It would need to be set through the constructor.

2024-02-08 05:19 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +     * @notice Append the auction group, each time when  the auction settleDuration or bitTime should be changed,
There's an extra space here: when  the

2024-02-08 06:31 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        claimableAmount = getClaimableAmount(auctionGroupId, auctionId, bidder);
fixed

2024-02-08 06:34 UTC, aristotleee commented on contracts/MineAuction.sol
> +    receive() external payable {
Fixed

2024-02-08 06:35 UTC, aristotleee commented on hardhat/test/auctions/mine.test.ts
> +  it('can bid when auction is skipped', async () => {})
Fixed

2024-02-08 06:37 UTC, aristotleee commented on contracts/MineAuction.sol
> +    uint256 public totalAuctionableAmount;
Moved it to constructor

2024-02-08 06:37 UTC, aristotleee commented on contracts/MineAuction.sol
> +    uint256 constant SECONDS_IN_FOUR_YEARS = 4 * SECONDS_IN_YEAR + 1;
Fixed

2024-02-08 06:37 UTC, aristotleee commented on contracts/MineAuction.sol
> +     * @notice Append the auction group, each time when  the auction settleDuration or bitTime should be changed,
Fixed

2024-02-08 08:15 UTC, StarDumpling commented on contracts/MineAuction.sol
> +     * and then validate  current time is in the middle of a auction, it should not be during a settlement, and it should
```suggestion
     * @dev both the group id and auction is are passed from the client, so the client should calculate the auction group id and auction id
     * we validate the auction group id and auction id, and then calculate the start time and end time of the auction,
     * and then validate current time is in the middle of a auction, it should not be during a settlement, and it should
```

2024-02-08 08:16 UTC, StarDumpling commented on contracts/MineAuction.sol
> +     *  bidToken *  ( rewardAmount / totalBidAmount ) - claimed
```suggestion
     * bidToken * ( rewardAmount / totalBidAmount ) - claimed
```

2024-02-08 12:00 UTC, aristotleee commented on hardhat/test/auctions/mine.test.ts
> +    it('allows to partial claim', async () => {})
N/A, removed

2024-02-08 12:37 UTC, aristotleee commented on contracts/interfaces/IMineAuction.sol
> +interface IMineAuction {
case added

2024-02-08 12:38 UTC, aristotleee commented on contracts/MineAuction.sol
> +     * and then validate  current time is in the middle of a auction, it should not be during a settlement, and it should
Fixed

2024-02-08 12:38 UTC, aristotleee commented on contracts/MineAuction.sol
> +     *  bidToken *  ( rewardAmount / totalBidAmount ) - claimed
Fixed

2024-02-08 12:43 UTC, StarDumpling commented on contracts/MineAuction.sol
> +     *  bidToken *  ( rewardAmount / totalBidAmount ) - claimed
There is still an extra space before `bidToken * ( rewardAmount / totalBidAmount ) - claimed`

2024-02-08 12:47 UTC, StarDumpling commented on hardhat/test/auctions/mine.test.ts
> +    it('allows to partial claim', async () => {})
I think we still allow partial claims. If so, we should have a test for that.

2024-02-08 12:52 UTC, aristotleee commented on hardhat/test/auctions/mine.test.ts
> +    it('allows to partial claim', async () => {})
the claim test is actually partial claim, there's no "full claim" function. I guess in production user will need to use actual claimable amount in UI

2024-02-08 12:53 UTC, aristotleee commented on contracts/MineAuction.sol
> +     *  bidToken *  ( rewardAmount / totalBidAmount ) - claimed
Fixed

2024-02-08 12:57 UTC, StarDumpling commented on hardhat/test/auctions/mine.test.ts
> +    it('allows to partial claim', async () => {})
Okay, got it.

2024-02-18 22:50 UTC, franklynot commented on contracts/MineAuction.sol
> +    function getRewardAmount(uint256 auctionGroupId) internal view returns (uint256) {
Let's make it consistent and use the `_` prefix for all internal functions.

2024-02-19 07:45 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function getRewardAmount(uint256 auctionGroupId) internal view returns (uint256) {
fixed

2024-02-20 07:03 UTC, timesaved12345 commented on contracts/MineAuction.sol
> +    uint256 constant SECONDS_IN_FOUR_YEARS = 4 * SECONDS_IN_YEAR + 1 days;
I think `SECONDS_IN_YEAR` is not used. So, maybe we can just set `SECONDS_IN_FOUR_YEARS` to 1461 days?

2024-02-20 07:05 UTC, timesaved12345 commented on contracts/MineAuction.sol
> +                auctionGroupId--;
`--auctionGroupId` is cheaper.

2024-02-20 07:08 UTC, timesaved12345 commented on contracts/MineAuction.sol
> +        bidDuration = auctionGroups[auctionGroupId].bidDuration;
For saving gas, maybe we can store `auctionGroups[auctionGroupId]` in a variable first?

2024-02-20 07:12 UTC, timesaved12345 commented on contracts/abstracts/Pausable.sol
>      bool public paused;
Maybe we can use value 1 and 2 instead of true and false to save gas, just like the lock?

2024-02-20 07:13 UTC, timesaved12345 commented on contracts/abstracts/Proxiable.sol
>      bool public initialized = false;
Initializing a bool to false is not necessary.

2024-02-20 09:21 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    uint256 constant SECONDS_IN_FOUR_YEARS = 4 * SECONDS_IN_YEAR + 1 days;
Can also just expand it assuming the compiler resolves the value, which I think it should

uint256 constant SECONDS_IN_FOUR_YEARS = 4 * 365 * 24 * 60 * 60 + 1 days;

2024-02-20 09:26 UTC, ivebeenherebefore commented on contracts/abstracts/Pausable.sol
>      bool public paused;
It's a little different here since the contract won't often be paused / unpaused. I think keeping it as a bool since this is public makes sense.

2024-02-20 09:33 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function setAuctionGroup(uint64 startTime, uint32 settleDuration, uint32 bidDuration) external override onlyOwner {
Let's rename this to addAuctionGroup

2024-02-20 09:41 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        AuctionGroup memory auctionGroup = auctionGroups[auctionGroupId];
It's possible this will return the wrong answer, because initialAuctionStartTime may be in the future. I think we could modify this to not use break:

            if (auctionGroups[auctionGroupId].startTime <= block.timestamp) {
                    AuctionGroup memory auctionGroup = auctionGroups[auctionGroupId];
return (auctionGroupId, auctionGroup.startTime, auctionGroup.settleDuration, auctionGroup.bidDuration);
            }
            }
            // outside of loop, revert

2024-02-20 09:49 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +        Auction storage auction = auctions[auctionGroupId][auctionId];
Can we test if it's cheaper gas to make this var memory instead of storage?

2024-02-20 10:19 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function claimTo(uint256 auctionGroupId, uint256 auctionId, address to, uint256 amount) external override {
Let's overload this function: 

    function claimTo(uint256 auctionGroupId, uint256 auctionId, address to, uint256 amount) external override {
->
    function claim(uint256 auctionGroupId, uint256 auctionId, uint256 amount, address to) external override {
    
    In hardhat tests, we need to disambiguate which claim we're calling so we should use this format:
    
          await expect(auction['claim(uint256,uint256,uint256)'](groupId, auctionId, 100))

      await expect(auction['claim(uint256,uint256,uint256,address)'](groupId, auctionId, 100, other.address))

2024-02-21 06:06 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    uint256 constant SECONDS_IN_FOUR_YEARS = 4 * SECONDS_IN_YEAR + 1 days;
fixed

2024-02-21 06:06 UTC, stardustPandora commented on contracts/MineAuction.sol
> +                auctionGroupId--;
fixed

2024-02-21 06:06 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        bidDuration = auctionGroups[auctionGroupId].bidDuration;
fixed

2024-02-21 06:13 UTC, stardustPandora commented on contracts/abstracts/Proxiable.sol
>      bool public initialized = false;
fixed

2024-02-21 06:24 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function setAuctionGroup(uint64 startTime, uint32 settleDuration, uint32 bidDuration) external override onlyOwner {
fixed

2024-02-21 06:24 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        AuctionGroup memory auctionGroup = auctionGroups[auctionGroupId];
fixed

2024-02-21 06:34 UTC, stardustPandora commented on contracts/MineAuction.sol
> +        Auction storage auction = auctions[auctionGroupId][auctionId];
c now easy way, since we need this mapping structure to keep data, and since it is a view function, so gas should be fine

2024-02-21 06:35 UTC, stardustPandora commented on contracts/MineAuction.sol
> +            AuctionGroup memory nextAuctionGroup = auctionGroups[auctionGroupId + 1];
fixed

2024-02-21 06:41 UTC, stardustPandora commented on contracts/MineAuction.sol
> +    function claimTo(uint256 auctionGroupId, uint256 auctionId, address to, uint256 amount) external override {
fixed

2024-02-21 09:51 UTC, ivebeenherebefore commented on contracts/MineAuction.sol
> +    function claimTo(uint256 auctionGroupId, uint256 auctionId, address to, uint256 amount) external override {
@stardustPandora I think we can change the parameter order to:

function claim(uint256 auctionGroupId, uint256 auctionId, uint256 amount, address to) external override {

2024-02-22 02:56 UTC, merged