WIP: Migrate from ETH to an ERC20 collateral token
UnitBanking/unit-smart-contracts pull request #11
Opened 2023-12-22 17:28 UTC by franklynot

2024-01-11 10:49 UTC, ivebeenherebefore requested changes

2024-01-11 10:49 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> + - replace all occurences of `IERC20.transferFrom` to a library call, which leverages OZ's `SafeERC20.safeTransferFrom`
Reminder to return actual transferred amount from safeTransferFrom so we can replace with pancaked snapshots if needed.

2024-01-11 10:49 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +    constructor(address collateralBurnAddress) {
Interesting... why is this set via constructor instead via initialize or constant?

2024-01-11 10:49 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +        collateralToken.transferFrom(msg.sender, address(this), collateralAmountIn);
This transfer from should use safeTransfer and return amount transferred. We should hoist this above line 122.

2024-01-11 10:49 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +        collateralToken.transfer(msg.sender, _getWithdrawalAmount(unitTokenAmount));
Also should use safeTransfer

2024-01-11 10:59 UTC, StarDumpling commented on contracts/BondingCurve.sol
> +    constructor(address collateralBurnAddress) {
It could not be immutable/constant if we set it in `initialize()` function. We agreed we'll use address zero for burning. But we use OZ's ERC20 contract and for test purposes we cannot use address zero for burning. It this case, we can still use address zero in prod, but for testing we can set any other address.

2024-01-11 11:15 UTC, franklynot commented on contracts/BondingCurve.sol
> +    constructor(address collateralBurnAddress) {
We're not using a constant, to provide an option for the deployer to set it as desired. Mainly, there are two options for burning of the collateral token - transfer to an inaccessible EOA (e.g. `address(0)`) or to a token sink (i.e. a burn contract).
The token sink will be deployed before this, so the address will be known and can be set in the constructor rather than in the initializer (and thus can be immutable).
We also have an option to set it to `address(0)` on networks where the collateral token supports sending to it.

2024-01-11 15:19 UTC, StarDumpling commented on contracts/BondingCurve.sol
> +        collateralToken.transferFrom(msg.sender, address(this), collateralAmountIn);
Done

2024-01-11 15:19 UTC, StarDumpling commented on contracts/BondingCurve.sol
> + - replace all occurences of `IERC20.transferFrom` to a library call, which leverages OZ's `SafeERC20.safeTransferFrom`
Done

2024-01-11 15:43 UTC, StarDumpling commented on contracts/BondingCurve.sol
> +        collateralToken.transfer(msg.sender, _getWithdrawalAmount(unitTokenAmount));
Done

2024-01-12 07:05 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +    constructor(address collateralBurnAddress) {
Hmm, okay... let's merge this first

2024-01-12 07:06 UTC, ivebeenherebefore approved these changes

2024-01-12 08:02 UTC, merged