WIP: Unit contraction auction
UnitBanking/unit-smart-contracts pull request #12
Opened 2024-01-12 08:49 UTC by StarDumpling

2024-01-28 07:08 UTC, ivebeenherebefore requested changes

2024-01-28 07:08 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +        TransferUtils.safeTransferFrom(collateralToken, address(bondingCurve), msg.sender, collateralAmount);
💬 Discussion
I could see this either way...
Since we're not sure of the amount of collateralAmount actually transferred to the user, should we check it and then compute the burn amount?

2024-01-28 07:08 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +    function sellUnit(uint256 unitAmount) external {
I think we should lock this function

2024-01-28 07:08 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +    function buyUnit(uint256 collateralAmount) external {
We should have a reentrancy lock here

2024-01-28 07:08 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +            (1000 - ((block.timestamp - _auctionState.startTime) / 1800 seconds))) / 1000;
Again the decay function here is linear vs exponential.

2024-01-28 07:56 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +    uint256 public startPriceBuffer;
This is only used for contraction, should we can it contractionPriceBuffer?

2024-01-29 17:57 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +        super.initialize();
This is a constructor, so will be executed on the implementation contract upon deployment. We want to make the implementation contract unusable (because we want to avoid the confusion of anyone using it instead of the proxied contract). To accomplish this, we call `super.initialize()`, which sets the `initialized` flag, so that it's not possible to properly initialize it. The `initiazize()` function will be called via the proxy and will properly initialize the (proxy) contract and will also set the `initialized` flag. Therefore, we must not call it from the constructor.

Likewise, we do no want to set the owner in the constructor.

2024-01-29 18:13 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +        bondingCurve.approveCollateralToken(collateralAmount);
> We could also initiate the transfer from the bondingCurve if we are going to go through the trouble of calling a specialized function from it anyways.

> It doesn't seem necessary to approve and then call transfer.

Exactly. That was the improvement we thought of right after this was pushed. 😅

This is now done.

2024-01-29 18:30 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +     * Locks the contract, to prevent the implementation contract from being used.
I reworded the comment for clarity (i.e. removed the word 'locks'). Please review.

2024-01-29 18:38 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +    uint256 public startPriceBuffer;
Done.

2024-01-30 11:36 UTC, StarDumpling commented on contracts/auctions/UnitAuction.sol
> +     * @param _maxDuration New max duration of a Unit contraction auction.
Fixed

2024-01-30 16:37 UTC, StarDumpling commented on contracts/auctions/UnitAuction.sol
> +    function sellUnit(uint256 unitAmount) external {
As far as I know, for now, we'll be using WETH as collateral token. Since it's a well known token that doesn't have any unexpected side effects, there's no additional benefit of having reentrancy lock here (as long as we use WETH). We added a comment, that in case of changing the collateral token, we must consider using a lock here.

2024-01-30 16:38 UTC, StarDumpling commented on contracts/auctions/UnitAuction.sol
> +    function buyUnit(uint256 collateralAmount) external {
As far as I know, for now, we'll be using WETH as collateral token. Since it's a well known token that doesn't have any unexpected side effects, there's no additional benefit of having reentrancy lock here (as long as we use WETH). We added a comment, that in case of changing the collateral token, we must consider using a lock here.

2024-01-31 07:08 UTC, timesaved12345 commented on contracts/auctions/UnitAuction.sol
> +    UnitToken public immutable unitToken;
Should we use interfaces `IBondingCurve` and `IUnitToken`(currently not exists) instead of `BondingCurve` and `UnitToken`?

2024-01-31 07:24 UTC, timesaved12345 commented on contracts/abstracts/BaseToken.sol
Function `BaseToken.permit()` has a parameter called `owner`, which is shadowing `Ownable.owner`. Suggest to rename the parameter and all occasions in the function to `_owner`.

2024-02-01 00:48 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +    UnitToken public immutable unitToken;
We were using `collateralToken` and the `UNITUSD_PRICE_PRECISION` constant, which were exposed by the contract only. I've added them to the `IBondingCurve` interface so we can use it.

I left the use of `UnitToken` for now. I'm not sure we'll add an interface for it.

2024-02-01 02:55 UTC, timesaved12345 commented on contracts/auctions/UnitAuction.sol
> +    UnitToken public immutable unitToken;
I would vote for adding an interface for UnitToken, as the contract inherits BaseToken which inherits a few other contracts, which make the interface not obvious for contracts or 3rd party to use it. Of course, IERC20 or IERC20Permit can be used as a handle of the token, but then some functions are not easily accessible. An interface can be handy for this.
Considering the generalisation with BaseToken, maybe we can use BaseToken or IBaseToken here instead?

2024-02-01 10:20 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +    UnitToken public immutable unitToken;
We'll add `IUnitToken` in a separate PR.

2024-02-01 23:01 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +    function setContractionAuctionMaxDuration(uint256 _maxDuration) external onlyOwner {
The impact of allowing updates to max duration while an auction is running doesn't appear that significant, especially when these changes will be triggered only by a governance vote + a time delay.
If an auction is running and max duration is increased, the auction just continues, for longer than set at launch, with price decay. If max duration is reduced to a shorter period than how long an auction is already running, the next bid will terminate it - this is the worst, or at least the most impactful case, that can happen. This forces a new auction with a new starting price (which might even be better for the user). Another words, governance can terminate an auction before its intended time.

On a side note, we should probably add input value validation to avoid malicious attempts to set max duration to extremely long or short periods of time.

If we set guards, so that these updates cannot be made while an auction is running, it's possible that we block such updates for days while the reserve ratio (RR) is in the wrong range. In this scenario once an auction ends, a new one starts immediately. A cycle that takes place until the system stabilizes and RR returns to a healthy range.

To implement it more efficiently, we'd add a state variable in the auction state struct to store the max duration that was in effect when an auction was launched so we can enforce it until the auction ends. We'd have to pack it in one slot with the other variables, probably reducing allocation for the start price.
In this case we'd allow updates to max duration at any point and the new value would only take effect when the next auction starts - the desired behavior.
The cost is added code complexity (albeit small) and a minor gas increase for storing more variables when an auction starts (which is covered by the user).

I think either the latter option or the current implementation are viable options. I don't have a strong preference, but I'm leaning towards leaving it as is. Perhaps we should consult the business to confirm that governance should be allowed to update max duration at any point, potentially cutting short or extending a running auction.

2024-02-01 23:02 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +    function setStartPriceBuffer(uint256 _startPriceBuffer) external onlyOwner {
The start price buffer (only used in contraction auction) can actually be set at any point, regardless of whether an auction is running, because its value is only used when an auction starts (as opposed to max duration, which is read every time we refresh auction state). Any time it's updated, the new value will take effect when the next auction starts, which is desired. This is the current implementation.

2024-02-01 23:04 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +            (1000 - ((block.timestamp - _auctionState.startTime) / 1800 seconds))) / 1000;
Linear was used as an optimization. We've now reverted to exponential, as gas reduction was not significant (in the order of 200 gas).

2024-02-04 22:35 UTC, franklynot commented on contracts/abstracts/BaseToken.sol
Fixed.

2024-02-04 23:53 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +        if (reserveRatioAfter >= ReserveRatio.HIGH_RR) {
Added quote functions.

2024-02-05 09:49 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +    function setContractionAuctionMaxDuration(uint256 _maxDuration) external onlyOwner {
I agree, changing the max duration here is not a serious issue. Let's leave it as is for now.

2024-02-05 09:51 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +        if (reserveRatioAfter >= ReserveRatio.HIGH_RR) {
We discussed adding a quote function that would allow for calculation of a maximum allowed trade size to make it easier for someone to complete partial execution.

Input would be max desired input amount, return value would be largest possible input amount and corresponding output amount.

2024-02-05 10:17 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +    function sellUnit(uint256 unitAmount) external {
My main concerns here are:

1. Not marking these functions as nonReentrant, going from a trusted to an untrusted token, and then forgetting to update these to nonReentrant
2. Forgetting to stay vigilant and evaluating if there's a reentrancy risk in functions as part of our audit process

For purposes of discussion, if we did create a tokenNonReentrant modifier but the modifier only had the implementation of: { 
_;
} how much extra gas would that incur? The same as a function jump?

2024-02-11 23:43 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +        if (reserveRatioAfter >= ReserveRatio.HIGH_RR) {
This has been added (see `quoteSellUnit()`).

2024-02-19 06:20 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +                ((collateralUsdOracle.getCollateralUsdPrice() * collateralToken.balanceOf(address(this))) *
This doesn't take into account the decimals in collateralToken

2024-02-19 06:23 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +        if (collateralAmount < unitCollateralValue) {
There is another implicit assumption that the decimals of the collateral token and the unit token are the same.

2024-02-19 06:59 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
>                      ((collateralToken.balanceOf(address(this)) - transferredCollateralAmount) *
I see we're dividing by UNITUSD_PRICE_PRECISION when we want to divide by UNIT_PRECISION, but maybe it's clearer if we define an additional constant?

2024-02-19 07:27 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +    function refreshState() public returns (uint256 reserveRatio, AuctionState memory _auctionState) {
If we wanted to refactor refreshState and refreshStateInMemory, we could define a new function called computeState which returns an enum which signals the post computation state (noop: 0, new contraction: 1, new expansion: 2, terminate: 3), then use switch statements in refreshState or refreshStateInMemory to apply the state.

2024-02-19 07:30 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +    function getMaxSellAmount() external view returns (uint256 maxUnitAmount, uint256 collateralAmount) {
We should keep the naming convention and rename this to getMaxSellUnitAmount() returns (uint256 unitAmountIn, uint256 collateralAmountOut)

2024-02-19 07:31 UTC, ivebeenherebefore commented on contracts/auctions/UnitAuction.sol
> +    function getCurrentSellPrice() external view returns (uint256 currentSellPrice) {
getCurrentSellPrice  -> getCurrentSellUnitPrice?

2024-02-19 10:41 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +    function _getUnitCollateralPrice(uint256 transferredCollateralAmount) internal view returns (uint256) {
Hmm, the decimals/precision of this function looks like it may vary:

(unwrap(_getUnitUsdPriceForTimestamp(block.timestamp)) * COLLATERALUSD_PRICE_PRECISION) /
                        collateralUsdOracle.getCollateralUsdPrice() -> is Precision(UnitUsdPrice)
                        
but...

((collateralToken.balanceOf(address(this)) - transferredCollateralAmount) *
                        UNITUSD_PRICE_PRECISION) / unitTotalSupply -> is Precision(Collateral)

2024-02-20 15:16 UTC, StarDumpling commented on contracts/auctions/UnitAuction.sol
> +    function getMaxSellAmount() external view returns (uint256 maxUnitAmount, uint256 collateralAmount) {
Renamed to `getMaxSellUnitAmount()`.

2024-02-20 15:16 UTC, StarDumpling commented on contracts/auctions/UnitAuction.sol
> +    function getCurrentSellPrice() external view returns (uint256 currentSellPrice) {
Renamed to `getCurrentSellUnitPrice `.

2024-02-21 20:04 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +    function getMaxSellAmount() external view returns (uint256 maxUnitAmount, uint256 collateralAmount) {
Also renamed the return variables.

2024-02-29 02:27 UTC, franklynot commented on contracts/auctions/UnitAuction.sol
> +    function refreshState() public returns (uint256 reserveRatio, AuctionState memory _auctionState) {
Done.

2024-02-29 02:28 UTC, franklynot commented on contracts/BondingCurve.sol
> +    function _getUnitCollateralPrice(uint256 transferredCollateralAmount) internal view returns (uint256) {
Fixed. Made the output precision consistent.

2024-03-07 07:27 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +                ((collateralUsdOracle.getCollateralUsdPrice() * collateralToken.balanceOf(address(this))) *
The return value here is in collateralToken precision not standard precision. It seems ProtocolConstants uses standard precision.

2024-03-07 07:27 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +        if (getReserveRatio() < ProtocolConstants.HIGH_RR) {
Precision mismatch

2024-03-07 07:27 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +            (((desiredRR * unitUsdPrice) - (collateralUsdPrice * unitCollateralPrice)) * STANDARD_PRECISION);
Hmm, I think there is a mismatch here:

((desiredRR * unitUsdPrice) - (collateralUsdPrice * unitCollateralPrice))
18*18 - 18*colPrecision

2024-03-07 07:27 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +    function _getUnitCollateralPrice(uint256 transferredCollateralAmount) internal view returns (uint256) {
Oh I thought we would keep this in collateral precision. I guess now it's 18

2024-03-07 12:46 UTC, franklynot commented on contracts/BondingCurve.sol
> +            (((desiredRR * unitUsdPrice) - (collateralUsdPrice * unitCollateralPrice)) * STANDARD_PRECISION);
Currently `unitCollateralPrice` is still in standard precision, so it checks out.

2024-03-08 07:07 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +        collateralAmount =
I'm getting different signs on my terms.

2024-03-08 07:24 UTC, ivebeenherebefore commented on contracts/BondingCurve.sol
> +    function _getUnitCollateralPrice(uint256 transferredCollateralAmount) internal view returns (uint256) {
Cool, it's fine to push it off

2024-03-08 13:58 UTC, merged