Tokens and deploy script
UnitBanking/unit-smart-contracts pull request #9
Opened 2023-11-16 08:46 UTC by aristotleee

2023-11-17 14:58 UTC, StarDumpling commented on contracts/abstracts/ERC20.sol
> +        address owner = msg.sender;
Logic Checklist 🍋
Common gas optimizations:
What is the purpose of this local `owner` variable?

2023-11-17 15:08 UTC, StarDumpling commented on contracts/abstracts/ERC20.sol
> +            unchecked {
Since it's unchecked operation, let's also add comment:
`// Overflow not possible: value <= currentAllowance.`

2023-11-20 13:34 UTC, StarDumpling commented on hardhat/test/mineToken/Owner.test.ts
> +  it('set owner', async () => {
Duplicate test with `'owner can transfer ownership'`

2023-11-20 13:37 UTC, StarDumpling commented on contracts/abstracts/Ownable.sol
> +    function _setOwner(address _owner) internal {
Logic Checklist
Zero address ❌
Should it be possible to set `address(0)` as the new owner?

2023-11-20 13:40 UTC, StarDumpling commented on hardhat/test/mineToken/Owner.test.ts
> +  it('other address can not transfer ownership', async () => {
typo
```suggestion
  it('other address cannot transfer ownership', async () => {
```

2023-11-20 13:45 UTC, StarDumpling commented on contracts/MineToken.sol
> +        if (totalSupply > MAX_SUPPLY) {
There's missing MAX_SUPPLY test. Please consider adding such test to `hardhat/test/mineToken/Mint.test.ts`

2023-11-20 13:49 UTC, StarDumpling commented on contracts/MineToken.sol
> +    function mint(address account, uint256 amount) public override {
There's missing `ERC20InvalidReceiver` test for `mint` function in `hardhat/test/mineToken/Mint.test.ts`.

2023-11-20 13:50 UTC, StarDumpling commented on hardhat/test/mineToken/Burn.test.ts
> +    expect(totalSupplyAfter).to.equal(totalSupplyBefore - amount)
We should also be verifying owner's MINE balance.

2023-11-20 13:52 UTC, StarDumpling commented on contracts/MineToken.sol
> +    function mint(address account, uint256 amount) public override {
Same thing for `burn` function.

2023-11-20 13:56 UTC, StarDumpling commented on hardhat/test/mineToken/MineToken.test.ts
> +    expect(balanceAfter - balanceBefore).to.equal(100)
We should also verify spender's MINE balance

2023-11-20 13:59 UTC, StarDumpling commented on hardhat/test/mineToken/MineToken.test.ts
> +    expect(balanceAfter - balanceBefore).to.equal(100)
We should also verify owner's MINE balance.

2023-11-20 14:01 UTC, StarDumpling commented on hardhat/test/mineToken/MineToken.test.ts
> +  it('allows transfer from other to another', async () => {
We should also verify owner's MINE balance. In general, we should be verifying all balances that could be modified.

2023-11-21 05:20 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +        address owner = msg.sender;
optimized

2023-11-21 05:20 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +            unchecked {
Added

2023-11-21 05:21 UTC, aristotleee commented on hardhat/test/mineToken/Owner.test.ts
> +  it('set owner', async () => {
removed

2023-11-21 05:21 UTC, aristotleee commented on contracts/abstracts/Ownable.sol
> +    function _setOwner(address _owner) internal {
Yes, we should check for zero addresses, test also added

2023-11-21 05:21 UTC, aristotleee commented on hardhat/test/mineToken/Owner.test.ts
> +  it('other address can not transfer ownership', async () => {
renamed test case names

2023-11-21 05:27 UTC, aristotleee commented on hardhat/test/mineToken/Mint.test.ts
> +  it('owner can mint', async () => {
Added in both mint and burn for both tokens

2023-11-21 05:52 UTC, aristotleee commented on contracts/MineToken.sol
> +    function mint(address account, uint256 amount) public override {
Added

2023-11-21 05:52 UTC, aristotleee commented on hardhat/test/mineToken/Burn.test.ts
> +    expect(totalSupplyAfter).to.equal(totalSupplyBefore - amount)
Fixed

2023-11-21 05:52 UTC, aristotleee commented on hardhat/test/mineToken/MineToken.test.ts
> +    expect(balanceAfter - balanceBefore).to.equal(100)
Fixed

2023-11-21 05:55 UTC, aristotleee commented on hardhat/test/mineToken/MineToken.test.ts
> +    expect(balanceAfter - balanceBefore).to.equal(100)
Fixed

2023-11-21 06:08 UTC, aristotleee commented on hardhat/test/mineToken/MineToken.test.ts
> +  it('allows transfer from other to another', async () => {
Fixed

2023-11-21 09:46 UTC, StarDumpling commented on contracts/MineToken.sol
> +        _mint(msg.sender, amount);
Logic Checklist
Logic 🍎
Hmm, after this change, only minters can mint tokens and only for themselves. We should allow minters (msg.sender) to mint for other accounts.

2023-11-21 10:20 UTC, ivebeenherebefore commented on contracts/abstracts/Upgradable.sol
> +abstract contract Upgradable is IUpgradable {
Unless there's a strong reason why we should break this into an abstract contract, I think it makes more sense to merge this into the Proxy contract.

2023-11-21 10:20 UTC, ivebeenherebefore commented on contracts/abstracts/Upgradable.sol
> +    function _getImplementation() internal view returns (address implementation) {
• Rename _getImplementation() -> _implementation()

2023-11-21 10:20 UTC, ivebeenherebefore commented on contracts/abstracts/Upgradable.sol
> +    function _setImplementation(address newImplementation) private {
• Can we rename arg address newImplementation -> address implementation or _implementation if there are concerns with shadowing?
• There may be times we want to set implementation without a call immediately afterwards:
   • Make internal
   • move emit Upgraded(newImplementation);

2023-11-21 10:20 UTC, ivebeenherebefore commented on contracts/abstracts/Upgradable.sol
> +    function _upgradeToAndCall(address newImplementation, bytes memory data) internal {
• Can we rename address newImplementation -> address implementation or _implementation if there are concerns with shadowing

2023-11-21 10:20 UTC, ivebeenherebefore commented on contracts/abstracts/Upgradable.sol
> +    function getAdmin() internal view returns (address admin) {
• Rename getAdmin() -> admin()

2023-11-21 10:20 UTC, ivebeenherebefore commented on contracts/abstracts/Upgradable.sol
> +    function _setAdmin(address newAdmin) private {
• Let's combine _setAdmin and _changeAdmin?

2023-11-21 10:20 UTC, ivebeenherebefore commented on contracts/Proxy.sol
> +contract Proxy is Upgradable {
Note to self: Once Proxy and Upgradable are combined, this needs to be reviewed again.

2023-11-21 10:29 UTC, StarDumpling commented on contracts/abstracts/Ownable.sol
> +    function setOwner(address _owner) external virtual onlyOwner {
It's already been fixed in 6816fe26bbe7f15e134619ad947f24341b0a38a8

2023-11-21 10:32 UTC, StarDumpling commented on contracts/test/BaseTokenTest.sol
> +contract BaseTokenTest is BaseToken {
`BaseToken` contract  should allow to specify `receiver` for `mint()` and `spender` for `burn()` functions. There's no need for this test contract

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +        _setMintable(msg.sender, true);
Let's not set msg.sender as default mineable and burnable. It's unlikely that we'll need this and we'll have to spend gas and txns to turn this off.

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +    function setMintable(address minter, bool mintable) external onlyOwner {
Setter Checklist ✅

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +    function mint(uint256 amount) external virtual {
Logic Checklist ✅

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +    function burn(uint256 amount) external virtual {
Logic Checklist ✅

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +        if (account == address(0)) {
Check is currently impossible to trigger

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +        if (!isMintable[msg.sender]) {
Discussion 💬
It seems to me that this check should be pushed into mintable._mint function and then we should call super:

function _mint(address account, uint256 amount) internal override {
       super._mint(account, amount); // check would be located here and would revert
       _update(address(0), account, amount);
}

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +        if (!isBurnable[address(0)] && !isBurnable[msg.sender]) {
Discussion 💬
It seems to me that this check should be pushed into burnable._burn function and then we should call super:

function _burn(address account, uint256 amount) internal override {
       super. _burn(account, amount); // check would be located here and would revert
       _update(account, address(0), amount);
}

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +        if (!isBurnable[address(0)] && !isBurnable[msg.sender]) {
Do we need an extra check here in this conditional? It's weird because this is an internal function but if it is to be used alone, this check should be added:

        if (!(isBurnable[msg.sender] || (isBurnable[address(0)] && account == msg.sender))) {
        
        if (!isBurnable[msg.sender] && !(isBurnable[address(0)] && account == msg.sender))) {

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/abstracts/ERC20.sol
> +    constructor() {
Let's make these required arguments in the constructor instead and pass them through. Because if for instance we use this in a proxy contract, the decimals in the implementation contract could differ from those in the proxy.

2023-11-21 12:26 UTC, ivebeenherebefore commented on contracts/UnitToken.sol
> +    constructor() BaseToken() {}
I think we should pass the name, symbol, and decimals to BaseToken -> Erc20 constructor here too.

2023-11-21 12:30 UTC, ivebeenherebefore commented on contracts/abstracts/ERC20.sol
> +abstract contract ERC20 is IERC20 {
Reminder to add signature based permit functionality: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Permit.sol

2023-11-21 15:14 UTC, StarDumpling commented on contracts/abstracts/BaseToken.sol
> +    function burn(uint256 amount) external virtual {
This function should also implement `function burn(address from, uint256 _amount)` and allow burning from a particular address

2023-11-21 15:46 UTC, StarDumpling commented on contracts/abstracts/BaseToken.sol
> +        if (!isBurnable[address(0)] && !isBurnable[msg.sender]) {
Or we can use allowance here

2023-11-22 08:16 UTC, aristotleee commented on contracts/abstracts/Burnable.sol
> +    event BurnableSet(address indexed burner, bool burnable);
Added

2023-11-22 08:17 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +    event MintableSet(address indexed minter, bool mintable);
Added

2023-11-22 08:17 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +    error MintableInvalidMinterAddress(address account);
Removed

2023-11-22 08:18 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +        if (minter == address(0)) {
It will save a storage write, it's the same idea of having 'Changed check' in setters
Removed anyways, looks cleaner as Burnable

2023-11-22 08:47 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +    function _approve(address owner, address spender, uint256 value) internal {
deleted

2023-11-22 08:48 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +                _approve(owner, spender, currentAllowance - value, false);
updating the storage directly will have no checks that lead to allowances storage filled with address(0) data

2023-11-22 08:55 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +        if (owner == address(0)) {
Will address(0) be saved to storage if we don't check this?

2023-11-22 08:56 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +        _spendAllowance(from, msg.sender, value);
_spendAllowance is now used in burnFrom in BaseToken

2023-11-22 09:05 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +        if (minter == address(0)) {
It could save an unnecessary storage write

2023-11-22 09:06 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +    error MintableInvalidMinterAddress(address account);
Removed argument

2023-11-22 09:40 UTC, aristotleee commented on contracts/abstracts/BaseToken.sol
> +        if (!isMintable[msg.sender]) {
it's reasonable to move the logic that belongs to mintable

2023-11-22 09:41 UTC, aristotleee commented on contracts/abstracts/BaseToken.sol
> +        if (account == address(0)) {
This check moved to burnFrom

2023-11-22 09:43 UTC, aristotleee commented on contracts/abstracts/BaseToken.sol
> +        if (account == address(0)) {
changed mint to allow mint for others

2023-11-22 09:43 UTC, aristotleee commented on contracts/abstracts/BaseToken.sol
> +    function mint(uint256 amount) external virtual {
Fixed

2023-11-22 09:43 UTC, aristotleee commented on contracts/abstracts/BaseToken.sol
> +    function burn(uint256 amount) external virtual {
Added a burnFrom function according to OZ

2023-11-22 09:44 UTC, aristotleee commented on contracts/MineToken.sol
> +        _mint(msg.sender, amount);
Fxied

2023-11-22 09:47 UTC, aristotleee commented on contracts/test/BaseTokenTest.sol
> +contract BaseTokenTest is BaseToken {
It is used as an implementation contract to test BaseToken common interfaces and internal functions

2023-11-22 10:14 UTC, aristotleee commented on contracts/test/UpgradedUnitToken.sol
> +contract UpgradedUnitToken is UnitToken {
Removed unused file

2023-11-22 10:14 UTC, aristotleee commented on contracts/test/ProxiableContractUpgraded.sol
> +// SPDX-License-Identifier: MIT
Fixed

2023-11-22 10:14 UTC, aristotleee commented on contracts/test/ProxiableContract.sol
> +contract ProxiableContract is Proxiable {
Fixed

2023-11-22 10:15 UTC, aristotleee commented on contracts/Deployer.sol
> +    event Deployed(address _address);
Fixed

2023-11-22 10:18 UTC, aristotleee commented on contracts/abstracts/Ownable.sol
> +    function setOwner(address _owner) external virtual onlyOwner {
It's already been fixed in https://github.com/UnitBanking/unit-smart-contracts/commit/6816fe26bbe7f15e134619ad947f24341b0a38a8

2023-11-22 11:01 UTC, aristotleee commented on contracts/interfaces/IProxiable.sol
> +    event DelegatedBy(address proxy);
Fixed

2023-11-22 11:01 UTC, aristotleee commented on contracts/interfaces/IProxiable.sol
> +    error ProxiableAlreadyDelegated();
Fixed

2023-11-22 11:02 UTC, aristotleee commented on contracts/interfaces/IProxiable.sol
> +    event DelegatedBy(address proxy);
Fixed

2023-11-22 11:02 UTC, aristotleee commented on contracts/interfaces/IProxiable.sol
> +    error ProxiableAlreadyDelegated();
Fixed

2023-11-22 11:02 UTC, aristotleee commented on contracts/abstracts/Proxiable.sol
> +    function initialize() public virtual override {
Fixed

2023-11-22 11:15 UTC, StarDumpling commented on contracts/abstracts/BaseToken.sol
> +        _spendAllowance(account, msg.sender, amount);
In line 43 `revert ERC20InvalidSender(address(0));` we call `account` sender, but in  line 45 `_spendAllowance(account, msg.sender, amount);` we call `msg.sender` sender. We should use other error here.

2023-11-22 11:24 UTC, StarDumpling commented on contracts/abstracts/BaseToken.sol
> +        }
Can we move it to `Mintable` contract? I believe we'll never want to mint to address(0).

2023-11-22 13:13 UTC, StarDumpling commented on contracts/MineToken.sol
> +    function mint(address account, uint256 amount) public override {
There's no `mint()` function test for MineToken contract.

2023-11-22 14:29 UTC, StarDumpling commented on contracts/MineToken.sol
> +        }
Logic Checklist
Zero address 🍋
Why is it not possible to delegate votes to default delegatee?
The test case for this error is called: `'should not be able to delegate to zero address'`? Should we assume that default delegatee will always be address(0)?

2023-11-23 02:34 UTC, franklynot requested changes

2023-11-23 02:34 UTC, franklynot commented on contracts/abstracts/Mintable.sol
> +            revert MintableDuplicatedOperation();
I suggest to reword for clarity to something along the lines of `MintableValueAlreadySet`.

2023-11-23 02:34 UTC, franklynot commented on contracts/abstracts/BaseToken.sol
> +        }
One case where that would be useful is if we wanted to increase total supply of a token without giving any specific address more tokens (i.e. dilute the token). Although that can be done by minting to any other known invalid address.

2023-11-23 02:34 UTC, franklynot commented on contracts/abstracts/ERC20.sol
> +    constructor() {
This is the implementation contract constructor. I suggest we don't set these values here to ensure it's not used. For tests we should set them in the inherited 'test' contract, or better yet, use a proxy to replicate production setup.

2023-11-23 02:34 UTC, franklynot commented on contracts/abstracts/ERC20.sol
> +    uint8 public override decimals;
They don't use a state variable to store it, because they return a hardcoded value. To do that, they just need to define a function that returns it.

The ERC20 standard defines this as a function too.

Here it's defined as a public state var, but the compiler implicitly generates a public getter function for it as well.

2023-11-23 05:23 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +    uint8 public override decimals;
Is it true that defining decimals hardcoded in solidity will make it deterministic at compile time, not possible to change it on chain?

Another fact is using public state variables e.g. name, symbol will prevent sub contracts to override the public getter functions generated implicitly

2023-11-23 05:44 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +    constructor() {
If we use arguments in constructor, we have to initialize them again during proxy initialization.
For decimals, I have change ERC20 abstract to use a public getter returning hardcoded value. Sub contracts will have to override the getter if decimals is different

In addition, since each of our token has a strong 'proxiable' requirement, I think it's OK to leave them as a common 'ERC20 Token' as the `name` when they are not under proxy, representing it's a not a valid Unit or Mine token.

2023-11-23 06:46 UTC, aristotleee commented on contracts/abstracts/Upgradable.sol
> +    function _setImplementation(address newImplementation) private {
Fixed partially
external interfaces `upgradeTo` and `upgradeToAndCall` already differentiate with or w/o call afterwards

2023-11-23 06:46 UTC, aristotleee commented on contracts/abstracts/Upgradable.sol
> +    function _getImplementation() internal view returns (address implementation) {
Fixed

2023-11-23 06:47 UTC, aristotleee commented on contracts/abstracts/Upgradable.sol
> +abstract contract Upgradable is IUpgradable {
Merged

2023-11-23 06:47 UTC, aristotleee commented on contracts/abstracts/Upgradable.sol
> +    function _upgradeToAndCall(address newImplementation, bytes memory data) internal {
Fixed

2023-11-23 06:47 UTC, aristotleee commented on contracts/abstracts/Upgradable.sol
> +    function getAdmin() internal view returns (address admin) {
Fixed

2023-11-23 06:47 UTC, aristotleee commented on contracts/abstracts/Upgradable.sol
> +    function _setAdmin(address newAdmin) private {
Fixed

2023-11-23 06:58 UTC, aristotleee commented on contracts/Deployer.sol
> +        emit Deployed(_address);
Will do
FYI, the salt will be a hashed value here

2023-11-23 07:02 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +            revert MintableDuplicatedOperation();
SameValueAlreadySet is more accurate IMO, it's quite hard to name this to be honest 😓

2023-11-23 10:40 UTC, aristotleee commented on contracts/abstracts/BaseToken.sol
> +    function burn(uint256 amount) external virtual {
Concluded with no need to burn from others

2023-11-23 10:43 UTC, aristotleee commented on contracts/UnitToken.sol
> +    constructor() BaseToken() {}
Use function overrides to change and represent name and symbol, state variables dropped

2023-11-23 11:00 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +        if (minter == address(0)) {
Concluded with not to remove this check

2023-11-23 11:00 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +    uint8 public override decimals;
Using function overrides and hardcoded name and symbols

2023-11-23 11:00 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +    constructor() {
Using function overrides and hardcoded name and symbols

2023-11-23 11:01 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +        if (owner == address(0)) {
Concluded with not to remove this check

2023-11-23 11:02 UTC, aristotleee commented on contracts/abstracts/BaseToken.sol
> +        _setMintable(msg.sender, true);
Removed

2023-11-23 11:44 UTC, aristotleee commented on contracts/abstracts/ERC20.sol
> +abstract contract ERC20 is IERC20 {
We already have delegateBySig in MineToken, I think we can extract this feature and have the permit (in another word approveBySig?) function implemented?

2023-11-24 06:54 UTC, aristotleee commented on contracts/abstracts/BaseToken.sol
> +        }
Moved to Mintable contract

2023-11-24 08:36 UTC, ivebeenherebefore commented on contracts/Deployer.sol
> +    error DeployerEmptyBytecode();
In summary, for errors:

• let's relocate errors to individual SCs instead of colocating them all in one file
• let's use the contract name as the namespace/prefix for all errors and try to use the ERC20 errors from this EIP as a standard: https://eips.ethereum.org/EIPS/eip-6093

2023-11-24 08:38 UTC, ivebeenherebefore commented on contracts/Deployer.sol
> +        if (size == 0) {
@franklynot what are some examples of networks with non-standard opcode implementations? Is it really necessary?

2023-11-24 08:43 UTC, ivebeenherebefore commented on contracts/abstracts/ERC20.sol
> +abstract contract ERC20 is IERC20 {
@aristotleee do you meanie should rename permit to approveBySig?

I think since permit is sort of a standard since OZ has an implementation for it, we should keep the suggested function stuff.

2023-11-24 15:08 UTC, StarDumpling commented on contracts/MineToken.sol
> +        return 'Mine Token';
```suggestion
        return 'Mine';
```

2023-11-24 15:08 UTC, StarDumpling commented on contracts/UnitToken.sol
> +        return 'Unit Token';
```suggestion
        return 'Unit';
```

2023-11-27 05:08 UTC, aristotleee commented on contracts/Deployer.sol
> +        if (size == 0) {
Fixed with checking create2 return address

2023-11-27 05:09 UTC, aristotleee commented on contracts/Deployer.sol
> +    function deploy(bytes memory bytecode, uint256 salt) external {
Added computeAddress

2023-11-27 05:11 UTC, aristotleee commented on contracts/Deployer.sol
> +contract Deployer {
Pausable added

2023-11-27 05:12 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +    function _setMintable(address minter, bool mintable) internal {
Fixed

2023-11-27 05:12 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +            revert MintableDuplicatedOperation();
Fixed with SameValueAlreadySet

2023-11-27 06:19 UTC, stardustPandora commented on contracts/MineToken.sol
> +        if (totalSupply > MAX_SUPPLY) {
added

2023-11-27 06:45 UTC, stardustPandora commented on contracts/MineToken.sol
> +    uint256 public constant MAX_SUPPLY = 1022700000 * 10 ** 18;
it costs less gas, fixed

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +            revert InvalidDelegateSignature(signatory);
Error needs to be renamed to be consistent with our naming conventions

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +    function _update(address from, address to, uint256 value) internal override {
Logic Checklist ✅

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +    function getCurrentVotes(address account) external view returns (uint256) {
Logic Checklist ✅

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +    function _setDefaultDelegatee(address _defaultDelegatee) internal {
What's the purpose of extracting this into a helper method? It seems we can combine it with the external function for now.

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +                uint32 fromRepNum = numCheckpoints[from];
Since these local vars are scoped, let's rename them for simplicity
fromRepNum -> nCheckpoints
fromRepOld -> oldVotes
fromRepNew -> newVotes

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +                uint32 toRepNum = numCheckpoints[to];
toRepNum -> nCheckpoints
toRepOld -> oldVotes
toRepNew -> newNotes

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +    function _moveDelegates(address from, address to, uint256 amount) internal {
It seems like _updateVotes would make the most sense naming wise, since our ERC20 contract also uses _update behind the scenes

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +        address currentDelegate = delegates[delegator];
This should be renamed as old to keep convention.
        address oldDelegatee = delegates[delegator];

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +    address public defaultDelegatee;
It seems both delegate and delegatee are nouns. We should pick one and stick with it. There's inconsistencies with usage in the code.

2023-11-27 07:19 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +        if (blockNumber > block.number) {
Condition should be >=. since the current block is still being mutated we don't know the total votes.

2023-11-27 08:01 UTC, stardustPandora commented on contracts/MineToken.sol
> +        if (block.timestamp >= expiry) {
cuz last time we agree on that user should not be able to delegate explicitly to default delegatee

2023-11-27 08:12 UTC, stardustPandora commented on contracts/MineToken.sol
> +        if (blockNumber > block.number) {
fixed

2023-11-27 08:13 UTC, stardustPandora commented on contracts/MineToken.sol
> +        address currentDelegate = delegates[delegator];
fixed

2023-11-27 08:33 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +        _updateVotes(delegates[from], delegates[to], uint96(value));
We should make sure that if we transfer tokens to Ana address that never set a delegate, the votes are transferred to the default delegate correctly

2023-11-27 11:39 UTC, StarDumpling commented on contracts/UnitToken.sol
> +        return 'Unit Token';
It's been fixed

2023-11-27 11:40 UTC, StarDumpling commented on contracts/MineToken.sol
> +        return 'Mine Token';
It's been fixed in 9e60e2462dbf634eaa2704e006ad0be9a5e3ce95

2023-11-27 11:48 UTC, StarDumpling commented on hardhat/test/mineToken/delegation.test.ts
> +      (await mine.balanceOf(other.address)) + (await mine.balanceOf(other.address))
I suppose we should be adding `owner` votes and `other` votes to get all votes of default delegatee
```suggestion
      (await mine.balanceOf(owner.address)) + (await mine.balanceOf(other.address))
```

2023-11-27 11:52 UTC, StarDumpling commented on hardhat/test/mineToken/delegation.test.ts
> +    expect(await mine.balanceOf(another.address)).to.equal(BigInt(100000) * BigInt(10) ** BigInt(18))
Let's also verify `other` mine balance
`expect(await mine.balanceOf(other.address)).to.equal(otherMineBalanceBefore - (BigInt(100000) * BigInt(10) ** BigInt(18)))`

2023-11-27 11:59 UTC, StarDumpling commented on hardhat/test/mineToken/basic.test.ts
> +describe('MineToken bascis', () => {
```suggestion
describe('MineToken basics', () => {
```

2023-11-27 12:23 UTC, StarDumpling commented on contracts/MineToken.sol
> +    function mint(address account, uint256 amount) public override {
It's been fixed in 50d62a56fe3f06c266eb76e93de228d458274c93 and 610660d59abfe75af379be0495f5b133e71feef7

2023-11-28 02:32 UTC, aristotleee commented on contracts/abstracts/Burnable.sol
> +    error BurnableUnauthorizedBurner(address account);
Fixed

2023-11-28 02:33 UTC, aristotleee commented on contracts/abstracts/Ownable.sol
> +    error OwnableInvalidOwnerAddress(address account);
Fixed

2023-11-28 02:33 UTC, aristotleee commented on contracts/abstracts/Ownable.sol
> +    error OwnableDuplicatedOperation();
Fixed

2023-11-28 02:33 UTC, aristotleee commented on contracts/abstracts/Ownable.sol
> +    error OwnableUnauthorizedAccount(address account);
Fixed

2023-11-28 02:34 UTC, aristotleee commented on contracts/interfaces/IProxy.sol
> +    error ProxyUnauthorized();
Fixed

2023-11-28 02:34 UTC, aristotleee commented on contracts/interfaces/IProxy.sol
> +    error ProxyDuplicatedOperation();
Fixed

2023-11-28 02:38 UTC, aristotleee commented on contracts/Proxy.sol
> +contract Proxy is IProxy {
The reason for `admin_` is there is already a `_admin()` internal function, which wraps assembly
Fixed with double underscore `__admin`

2023-11-28 02:42 UTC, aristotleee commented on contracts/interfaces/IVote.sol
> +    event DelegateChanged(address indexed delegator, address indexed fromDelegate, address indexed toDelegate);
Fixed by @stardustPandora

2023-11-28 02:46 UTC, aristotleee commented on hardhat/test/mineToken/basic.test.ts
> +describe('MineToken bascis', () => {
Fixed

2023-11-28 08:27 UTC, aristotleee commented on contracts/abstracts/Mintable.sol
> +    function mint(address receiver, uint256) public virtual {
it's the solc that complains.

```suggestion
    function mint(address receiver, uint256 /* amount */) public virtual {
```
Fixed with wrapping argument name with block comment

2023-11-28 08:28 UTC, aristotleee commented on contracts/abstracts/Burnable.sol
> +    function burn(uint256) public virtual {
Fixed with wrapping argument name with block comment

2023-11-28 08:29 UTC, aristotleee commented on contracts/MineToken.sol
> +    mapping(address => address) public delegatees;
Added key/value names

2023-11-28 08:30 UTC, aristotleee commented on .env.sample
> +SEPOLIA_URL = https://sepolia.infura.io/v3/<key>
Added

2023-11-29 03:52 UTC, stardustPandora commented on hardhat/test/mineToken/delegation.test.ts
> +      (await mine.balanceOf(other.address)) + (await mine.balanceOf(other.address))
fixed

2023-11-29 12:27 UTC, StarDumpling commented on hardhat/test/mineToken/delegation.test.ts
> +    expect(await mine.balanceOf(another.address)).to.equal(BigInt(100000) * BigInt(10) ** BigInt(18))
It's been fixed in 42ee93dcbf1492a812dac245f116ec4af90de5ab

2023-11-29 12:52 UTC, stardustPandora commented on contracts/MineToken.sol
> +        }
fixed

2023-11-29 23:55 UTC, franklynot commented on contracts/abstracts/BaseToken.sol
> +        _approve(signatory, spender, value, true);
Looks like we're missing a check for `signatory != owner`. We need to verify that the signature comes from the owner of the token.

2023-11-29 23:55 UTC, franklynot commented on contracts/abstracts/BaseToken.sol
> +        uint256 nonce,
We have the current nonce in `nonces[signatory]`. No need for the caller to pass it.

2023-11-30 12:52 UTC, StarDumpling commented on contracts/abstracts/BaseToken.sol
> +        uint256 nonce,
In `delegateBySig()` function we verify if `nonce != nonces[signatory]++`. Why shouldn't we verify it here in `permit()` function?

2023-11-30 15:08 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +            checkpoints[delegatee][nCheckpoints - 1].votes = uint96(newVotes);
@stardustPandora 
Is this cast of votes from uint256 to uint96 checked?

2023-11-30 15:33 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +        uint256 nonce,
This implementation of permit also doesn't pass nonce: https://github.com/soliditylabs/ERC20-Permit/blob/7348a4f5cb34bb7b6e40200506b99f3f2b4c9e58/contracts/ERC20Permit.sol#L63

2023-11-30 15:34 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +    function delegateBySig(address delegatee, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s) external {
Based on ERC20.permit, we should consider if nonce should be passed here or not

2023-11-30 17:48 UTC, StarDumpling commented on contracts/MineToken.sol
> +    function delegateBySig(address delegatee, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s) external {
`delegateBySig()` in OZ takes `nonce` as function argument https://github.com/OpenZeppelin/openzeppelin-contracts/blob/552cffde563e83043a6c3a35012b626a25eba775/contracts/governance/utils/Votes.sol#L142

Do you know why in `permit()` they don't pass `nonce`?

2023-12-01 14:46 UTC, StarDumpling commented on contracts/MineToken.sol
> +    function delegateBySig(address delegatee, uint256 nonce, uint256 expiry, uint8 v, bytes32 r, bytes32 s) external {
After analysing OZ's contracts history with @franklynot , we assume they don't pass and verify `nonce` in `permit()` since it's redundant check. As @franklynot said, there's no need to pass `nonce` to neither `permit()` nor `delegateBySig()`.

2023-12-04 05:49 UTC, ivebeenherebefore commented on contracts/abstracts/Pausable.sol
> +abstract contract Pausable {
💬 Discussion
• I see this is from OZ but it's out of style with the rest of our code.
• Normally we would do setPaused, PausedSet, etc, etc

2023-12-04 06:26 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +        _approve(signatory, spender, value, true);
Agreed, we need to ensure that the signer is the owner.

2023-12-04 06:46 UTC, ivebeenherebefore commented on contracts/abstracts/BaseToken.sol
> +        _approve(signatory, spender, value, true);
@stardustPandora @aristotleee

2023-12-04 08:09 UTC, franklynot commented on foundry/script/Counter.s.sol
This is a Foundry example file, please remove.

2023-12-04 08:09 UTC, franklynot commented on foundry/test/Counter.t.sol
This is a Foundry example file, please remove.

2023-12-04 08:36 UTC, ivebeenherebefore commented on contracts/MineToken.sol
> +        if(newVotes > type(uint96).max) {
Add a comment that this is not actually needed.

2023-12-05 04:54 UTC, merged